### ISSUE TITLE
obsidian 1.6.2: this plugin is not working.

### ISSUE THREAD

**Issue by bibibimartyr** [Richardsl/heatmap-calendar-obsidian#124]
v1.6.2:<img width="926" alt="截屏2024-06-08 14 06 04" src="https://github.com/Richardsl/heatmap-calendar-obsidian/assets/49381756/83b3586c-616b-4452-9de8-563d10e17371">

v1.5.12:![IMG_0007](https://github.com/Richardsl/heatmap-calendar-obsidian/assets/49381756/5507b711-c02e-4ff3-a157-5e3448f84391)

**Comment by dmissoh** [comment]
I'm having the same issue.

**Comment by imperiumprunum** [comment]
Stopped working yesterday, with no changes into code introduced. 
![heatmap_issue](https://github.com/Richardsl/heatmap-calendar-obsidian/assets/42384893/c63507b4-20fb-4bd8-90e2-171c84624417)

**Comment by ckpinguin** [comment]
Same here, I currently have no idea where to start debugging this. No errors or warnings from the plugin in console. Rendering is happening for the icons (if configured) but not for the colors.

**Comment by lksrpp** [comment]
It can be solved with a line of custom css code: https://github.com/Richardsl/heatmap-calendar-obsidian/issues/118#issuecomment-2156027243

**Comment by BRobsidian** [comment]
Ok, i'm not a dev or something, i don't know nothing about code, but i could solve the problem after some couple minutes thought some issue sections about heatmap.
I've installed Visual Studio Code, then i went to my vault folder -> .obsidian -> plugins -> heatmap-calendar -> styles.css
Once i opened styles.css with Visual Studio Code, i searched for ".heatmap-calendar-boxes li {" , and i added those lines:

height: 100%;
margin-inline-start: 0 !important;

After all this, i closed the file, restarted obsidian and heatmap was working again.

I think this happened because of obsidian update, so i turn-off the option "Automatic updates" (settings-> general), cause it took me more than 1 hour to solve a lot of different problems i had with community plugins..

Btw, thanks for who suggested the custom css .heatmap-calendar-boxes li { margin-inline-start: 0 !important; }

**Comment by MrTakizawa** [comment]
This issue is solved already.
Plz check the **https://github.com/Richardsl/heatmap-calendar-obsidian/issues/118#issuecomment-2156027243**
